### ISSUE TITLE
Compile-Error: comma at end of enumerator list.

### ISSUE THREAD

**Issue by GreenFoxLight** [mrvn/raspbootin#5]
Compiling the source leads to a error:
uart.cc:62:36: error: comma at end of enumerator list [-pedantic]
Simply removing the comma fixes the issue and compiles successfully.

**Comment by mrvn** [comment]
There is no -pedantic in the default CXXFLAGS so this is something you broke.

The comma at the end is there for a purpose. Specifically when more values are added to the enum at a later time the current last one doesn't have to be edited to add a comma. It therefore will not show up in diffs. This makes it easier to see what actually changed. I will probably never happen for the uart but that's my coding style.
